name: CMake

on:
  push:
  pull_request:
    branches: [ dev ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - name: Fetch Submodules
      run: git submodule update --init


    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/install
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target examples check --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C ${{env.BUILD_TYPE}}      
